const { cmd, commands } = require('../command');
const os = require("os");
const { runtime } = require('../lib/functions');

cmd({
    pattern: "alive",
    alias: ["status", "runtime", "uptime"],
    desc: "Check uptime and system status",
    category: "main",
    react: "🧚‍♂️",
    filename: __filename
},
async (conn, mek, m, { from, quoted, body, isCmd, command, args, q, isGroup, sender, senderNumber, botNumber2, botNumber, pushname, isMe, isOwner, groupMetadata, groupName, participants, groupAdmins, isBotAdmins, isAdmins, reply }) => {
    try {
        const uptime = runtime(process.uptime());
        const ram = `${(process.memoryUsage().heapUsed / 1024 / 1024).toFixed(2)}MB / ${(os.totalmem() / 1024 / 1024).toFixed(2)}MB`;
        const hostname = os.hostname();

        // ඔයා ඉල්ලපු විදිහටම යටින් Generated by DENETH-MD වැකිය ඉමෝජිත් සමඟ එකතු කළා
        const status = `👋 *HELLO ${pushname} I AM ALIVE NOW*

╭━━〔 *DENETH-MD* 〕━━┈⊷
┃◈╭────────────
┃◈┃• *⏳ Uptime*: ${uptime}
┃◈┃• *📟 Ram usage*: ${ram}
┃◈┃• *⚙️ HostName*: ${hostname}
┃◈┃• *👨‍💻 Owner*: DENETH MD
┃◈┃• *🧬 Version*: 3.0.0 BETA
┃◈└───────────
╰──────────────

> *Generated by DENETH-MD* 🤖⚡`;

        // =================================================================
        // FORCE INTERACTIVE STRUCTURE (NO BUTTONS, SHOWS VERSION ERROR)
        // =================================================================
        const { generateWAMessageFromContent, proto } = require("@whiskeysockets/baileys");

        const msg = generateWAMessageFromContent(from, {
            viewOnceMessage: {
                message: {
                    messageContextInfo: {
                        deviceListMetadata: {},
                        deviceListMetadataVersion: 2
                    },
                    interactiveMessage: proto.Message.InteractiveMessage.fromObject({
                        body: proto.Message.InteractiveMessage.Body.fromObject({
                            text: status
                        }),
                        footer: proto.Message.InteractiveMessage.Footer.fromObject({
                            text: "© Powered By Deneth MD"
                        }),
                        header: proto.Message.InteractiveMessage.Header.fromObject({
                            title: "✨ DENETH MD ALIVE STATUS ✨",
                            hasMediaAttachment: false
                        }),
                        carouselMessage: proto.Message.InteractiveMessage.CarouselMessage.fromObject({
                            cards: [
                                proto.Message.InteractiveMessage.fromObject({
                                    body: proto.Message.InteractiveMessage.Body.fromObject({ text: "" }),
                                    nativeFlowMessage: proto.Message.InteractiveMessage.NativeFlowMessage.fromObject({
                                        buttons: [] // බටන්ස් පෙනෙන්න නැති වෙන්න හිස්ව තැබුවා
                                    })
                                })
                            ]
                        }),
                        contextInfo: {
                            mentionedJid: [m.sender],
                            forwardingScore: 999,
                            isForwarded: true,
                            forwardedNewsletterMessageInfo: {
                                newsletterJid: '120363429118791328@newsletter',
                                newsletterName: 'DENETH MD',
                                serverMessageId: 143
                            }
                        }
                    })
                }
            }
        }, { userJid: conn.user.jid, quoted: mek }); // conn ලෙස නිවැරදි කර ඇත

        // මැසේජ් එක වට්ස්ඇප් වෙත බලෙන් යැවීම (පරණ අනුවාද වලට බ්ලොක් මැසේජ් එකක් ලෙස පෙනේ)
        await conn.relayMessage(from, msg.message, { messageId: msg.key.id }); // conn ලෙස නිවැරදි කර ඇත

    } catch (e) {
        console.error("Error in alive command:", e);
        reply(`❌ An error occurred: ${e.message}`);
    }
});
