const { cmd, commands } = require('../command');
const os = require("os");
const { runtime } = require('../lib/functions');

cmd({
    pattern: "alive",
    alias: ["status", "runtime", "uptime"],
    desc: "Check uptime and system status",
    category: "main",
    react: "🧚‍♂️",
    filename: __filename
},
async (conn, mek, m, { from, quoted, body, isCmd, command, args, q, isGroup, sender, senderNumber, botNumber2, botNumber, pushname, isMe, isOwner, groupMetadata, groupName, participants, groupAdmins, isBotAdmins, isAdmins, reply }) => {
    try {
        const uptime = runtime(process.uptime());
        const ram = `${(process.memoryUsage().heapUsed / 1024 / 1024).toFixed(2)}MB / ${(os.totalmem() / 1024 / 1024).toFixed(2)}MB`;
        const hostname = os.hostname();

        // 🖼️ ඔයාට කැමති Image URL එකක් මෙතනට දාන්න (Direct Link එකක් වෙන්න ඕනේ)
        const imageUrl = "https://ibb.co"; 

        const status = `👋 *HELLO ${pushname} I AM ALIVE NOW*

╭━━〔 *DENETH-MD* 〕━━┈⊷
┃◈╭────────────
┃◈┃• *⏳ Uptime*: ${uptime}
┃◈┃• *📟 Ram usage*: ${ram}
┃◈┃• *⚙️ HostName*: ${hostname}
┃◈┃• *👨‍💻 Owner*: DENETH MD
┃◈┃• *🧬 Version*: 3.0.0 BETA
┃◈└───────────
╰──────────────

> *Generated by DENETH-MD* 🤖⚡`;

        // =================================================================
        // NATIVE FLOW INTERACTIVE BUTTONS WITH IMAGE HEADER (PATHUMTECH)
        // =================================================================
        const { generateWAMessageFromContent, proto } = require("@whiskeysockets/baileys");

        const buttons = [
            {
                "name": "quick_reply",
                "buttonParamsJson": JSON.stringify({
                    "display_text": "MAIN MENU 📜",
                    "id": ".menu"
                })
            },
            {
                "name": "quick_reply",
                "buttonParamsJson": JSON.stringify({
                    "display_text": "PING ⚡",
                    "id": ".ping"
                })
            }
        ];

        // Image එක Header එකක් විදිහට සකස් කිරීම
        const mediaMessage = await conn.prepareWAMessageMedia({ image: { url: imageUrl } }, { upload: conn.waUploadToServer });

        const msg = generateWAMessageFromContent(from, {
            viewOnceMessage: {
                message: {
                    messageContextInfo: {
                        deviceListMetadata: {},
                        deviceListMetadataVersion: 2
                    },
                    interactiveMessage: proto.Message.InteractiveMessage.fromObject({
                        body: proto.Message.InteractiveMessage.Body.fromObject({
                            text: status
                        }),
                        footer: proto.Message.InteractiveMessage.Footer.fromObject({
                            text: "© Powered By Deneth MD"
                        }),
                        header: proto.Message.InteractiveMessage.Header.fromObject({
                            title: "✨ DENETH MD ALIVE STATUS ✨",
                            hasMediaAttachment: true,
                            imageMessage: mediaMessage.imageMessage // මෙතනින් තමයි බ්ටන් එකට උඩින් ඉමේජ් එක සෙට් වෙන්නේ
                        }),
                        nativeFlowMessage: proto.Message.InteractiveMessage.NativeFlowMessage.fromObject({
                            buttons: buttons
                        }),
                        contextInfo: {
                            mentionedJid: [m.sender],
                            forwardingScore: 999,
                            isForwarded: true,
                            forwardedNewsletterMessageInfo: {
                                newsletterJid: '120363429118791328@newsletter',
                                newsletterName: 'DENETH MD',
                                serverMessageId: 143
                            }
                        }
                    })
                }
            }
        }, { userJid: conn.user.jid, quoted: mek });

        // මැසේජ් එක WhatsApp වෙත යැවීම
        await conn.relayMessage(from, msg.message, { messageId: msg.key.id });

    } catch (e) {
        console.error("Error in alive command:", e);
        reply(`❌ An error occurred: ${e.message}`);
    }
});
