const { cmd } = require("../command");

cmd(
  {
    pattern: "animeDownload",
    alias: ["andl", "animedl"],
    react: "🎥",
    desc: "Get Direct Download Link for Anime Episode using Apify Actor.",
    category: "download",
    filename: __filename,
  },
  async (
    robin,
    mek,
    m,
    { from, quoted, body, isCmd, command, args, q, isGroup, sender, reply }
  ) => {
    try {
      if (!q) return reply("❌ *Please provide a valid anime name or link!*");

      const targetJid = typeof from === 'string' ? from : (mek.key.remoteJid || String(from));

      // 1. ඩවුන්ලෝඩ් ලින්ක් එක සැකසීමේ මැසේජ් එක යැවීම
      const loadingMsg = await robin.sendMessage(targetJid, { 
        text: `🎥 *DENETH-MD Processing Anime Download Link...*\n> *Please wait...* ⏳` 
      }, { quoted: mek });

      // ඔයා ලබා දුන් Apify Console ලින්ක් එක සෘජුවම ඇතුළත් කිරීම
      const apifyConsoleUrl = "https://console.apify.com/actors/pmNLr1QtlHcp5HM2J/input?addFromActorId=pmNLr1QtlHcp5HM2J";

      // ලින්ක් එකෙන් ඇනිමේ එකේ නම දළ වශයෙන් වෙන් කර හදාගැනීම
      let animeTitle = q.trim();
      if (animeTitle.includes("anime/")) {
        animeTitle = animeTitle.split("anime/").pop().split("/").replace(/-/g, " ");
      }
      animeTitle = animeTitle.split(" ").map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(" ");

      // 2. පරිශීලකයාට ඩවුන්ලෝඩ් ලින්ක් එක මැසේජ් එකක් ලෙස යැවීම
      let downloadMessage = `🎬 *DENETH-MD ANIME DOWNLOAD PANEL* 🎬\n\n`;
      downloadMessage += `📝 *Anime:* ${animeTitle}\n`;
      downloadMessage += `🚀 *Apify Console Download Link:* \n${apifyConsoleUrl}\n\n`;
      downloadMessage += `> *Click the link above to download your anime episode via Apify!* 🎥\n`;
      downloadMessage += `> *Generated by DENETH-MD* 🚀`;

      await robin.sendMessage(targetJid, { text: `✅ *Download Link Generated Successfully!*` }, { edit: loadingMsg.key });

      await robin.sendMessage(
        targetJid,
        { text: downloadMessage },
        { quoted: mek }
      );

    } catch (e) {
      console.error(e);
      reply(`❌ Error: ${e.message}`);
    }
  }
);
