const { cmd } = require("../command");
const axios = require("axios");

cmd(
  {
    pattern: "animedetails",
    alias: ["anime", "searchanime"],
    react: "🎭",
    desc: "Search Anime and send the video file directly without options.",
    category: "anime",
    filename: __filename,
  },
  async (
    robin,
    mek,
    m,
    { from, quoted, body, isCmd, command, args, q, sender, reply }
  ) => {
    try {
      if (!q) return reply("⚠️ *Please provide an anime name!* (Example: .animedetails naruto)");

      const targetJid = typeof from === 'string' ? from : (mek.key.remoteJid || String(from));

      // ඇනිමේ ලින්ක් එකක් දුන්නොත් නම විතරක් වෙන් කර ගැනීම
      let query = q.trim();
      if (query.includes("anime/")) {
        query = query.split("anime/").pop().split("/")[0].replace(/-/g, " ");
      }

      // 1. ඇනිමේ විස්තර සෙවීම ආරම්භ කිරීමේ මැසේජ් එක
      const loadingMsg = await robin.sendMessage(targetJid, { 
        text: `🎭 *DENETH-MD Searching Anime:* \`"${query}"\`\n> *Fetching details and video...* ⏳` 
      }, { quoted: mek });

      // 2. නොමිලේ දෙන විශ්වාසවන්ත Jikan API එකෙන් විස්තර සෙවීම
      const apiUrl = `https://jikan.moe{encodeURIComponent(query)}&limit=1`;
      const response = await axios.get(apiUrl);
      
      if (!response.data || !response.data.data || response.data.data.length === 0) {
        return await robin.sendMessage(targetJid, { 
          text: "❌ *Anime details not found! Please check the name and try again.*", 
          edit: loadingMsg.key 
        });
      }

      const anime = response.data.data[0];

      // ඇනිමේ විස්තර Format කිරීම
      let desc = `🎭 *DENETH-MD ANIME DOWNLOADER* 🎭

🎬 *Title:* ${anime.title}
⭐ *Rating:* ${anime.score || "N/A"} / 10
🎥 *Total Episodes:* ${anime.episodes || "Unknown"}
📅 *Status:* ${anime.status || "N/A"}
🎭 *Genres:* ${anime.genres ? anime.genres.map(g => g.name).join(", ") : "N/A"}

> *Downloading the Anime Episode... Please wait!* ⏳`;

      // විස්තර වෙනම මැසේජ් එකක් ලෙස යැවීම
      await robin.sendMessage(targetJid, { text: `✅ *Anime Found! Sending details...*` }, { edit: loadingMsg.key });

      const imageUrl = anime.images?.jpg?.image_url || "https://ibb.co";
      await robin.sendMessage(
        targetJid,
        { image: { url: imageUrl }, caption: desc },
        { quoted: mek }
      );

      // 3. ඔයාගේ Apify සෘජු ඩවුන්ලෝඩ් ලින්ක් එක (Direct Download Link)
      const downloadUrl = "https://apify.com";

      // 4. නම්බර්ස් කිසිවක් නැතිව කෙලින්ම වට්සැප් එකට වීඩියෝ ෆයිල් එක (Document) යැවීම
      await robin.sendMessage(
        targetJid,
        { 
          document: { url: downloadUrl }, 
          mimetype: "video/mp4", 
          fileName: `${anime.title}_Episode.mp4`, 
          caption: `🎥 *${anime.title} Main Episode* \n\n> *Generated by DENETH-MD* 🚀` 
        },
        { quoted: mek }
      );

    } catch (e) {
      console.error(e);
      reply(`❌ Error: ${e.message}`);
    }
  }
);
