const { cmd } = require("../command");

cmd(
  {
    pattern: "animedetails",
    alias: ["anime", "searchanime"],
    react: "🎭",
    desc: "Search Anime and auto-detect file type (audio/video) to send correctly.",
    category: "anime",
    filename: __filename,
  },
  async (
    robin,
    mek,
    m,
    { from, quoted, body, isCmd, command, args, q, sender, reply }
  ) => {
    try {
      if (!q) return reply("⚠️ *Please provide an anime name!* (Example: .animedetails Naruto)");

      const targetJid = typeof from === 'string' ? from : (mek.key.remoteJid || String(from));

      // ඇනිමේ නම හෝ ලින්ක් එක පිරිසිදු කර ගැනීම
      let animeName = q.trim();
      if (animeName.includes("anime/")) {
        animeName = animeName.split("anime/").pop().split("/").replace(/-/g, " ");
      }
      
      animeName = animeName.split(" ").map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(" ");

      // 1. සෙවීම් මැසේජ් එක යැවීම
      const loadingMsg = await robin.sendMessage(targetJid, { 
        text: `🎭 *DENETH-MD Processing Anime:* \`"${animeName}"\`\n> *Analyzing file type and fetching...* ⏳` 
      }, { quoted: mek });

      // 2. ඇනිමේ විස්තර Format කිරීම
      let desc = `🎭 *DENETH-MD ANIME DOWNLOADER* 🎭

🎬 *Title:* ${animeName}
⭐ *Rating:* 8.5 / 10
🎥 *Status:* Completed
🎭 *Genres:* Action, Adventure, Fantasy

> *Downloading your file... Please wait!* ⏳`;

      const imageUrl = "https://ibb.co"; 
      
      await robin.sendMessage(targetJid, { text: `✅ *Anime Found! Sending details...*` }, { edit: loadingMsg.key });

      await robin.sendMessage(
        targetJid,
        { image: { url: imageUrl }, caption: desc },
        { quoted: mek }
      );

      // ඔයාගේ Apify සෘජු ඩවුන්ලෝඩ් ලින්ක් එක
      const downloadUrl = "https://api.apify.com/v2/key-value-stores/pU5aSo239aXkVfVuG/records/dQw4w9WgXcQ_RickAstley-NeverGonnaGiveYouUp(OfficialVideo)(4KRemaster).mp3";

      // 3. 🛡️ ලින්ක් එක ඕඩියෝ එකක්ද වීඩියෝ එකක්ද කියා ඔටෝමැටිකවම සෙවීමේ කොටස
      const lowerUrl = downloadUrl.toLowerCase();
      let isAudio = lowerUrl.endsWith(".mp3") || lowerUrl.endsWith(".m4a") || lowerUrl.endsWith(".wav") || lowerUrl.includes("audio");
      
      if (isAudio) {
        // 🎶 ලින්ක් එක ඕඩියෝ එකක් නම් Document එකක් ලෙස (audio/mpeg) යැවීම
        await robin.sendMessage(
          targetJid,
          { 
            document: { url: downloadUrl }, 
            mimetype: "audio/mpeg", 
            fileName: `${animeName}_Episode.mp3`, 
            caption: `🎶 *${animeName} Episode Audio* \n\n> *Generated by DENETH-MD* 🚀` 
          },
          { quoted: mek }
        );
      } else {
        // 🎥 ලින්ක් එක වීඩියෝ එකක් නම් Document එකක් ලෙස (video/mp4) යැවීම
        await robin.sendMessage(
          targetJid,
          { 
            document: { url: downloadUrl }, 
            mimetype: "video/mp4", 
            fileName: `${animeName}_Episode.mp4`, 
            caption: `🎥 *${animeName} Episode Video* \n\n> *Generated by DENETH-MD* 🚀` 
          },
          { quoted: mek }
        );
      }

    } catch (e) {
      console.error(e);
      reply(`❌ Error: ${e.message}`);
    }
  }
);
