const { cmd } = require("../command");

cmd(
  {
    pattern: "animedetails",
    alias: ["anime", "searchanime"],
    react: "🎭",
    desc: "Search Anime and send the video file directly without external API dependencies.",
    category: "anime",
    filename: __filename,
  },
  async (
    robin,
    mek,
    m,
    { from, quoted, body, isCmd, command, args, q, sender, reply }
  ) => {
    try {
      if (!q) return reply("⚠️ *Please provide an anime name!* (Example: .animedetails Naruto)");

      const targetJid = typeof from === 'string' ? from : (mek.key.remoteJid || String(from));

      // ඇනිමේ ලින්ක් එකක් දුන්නොත් හෝ නමක් දුන්නොත් එය පිරිසිදු කර ගැනීම
      let animeName = q.trim();
      if (animeName.includes("anime/")) {
        animeName = animeName.split("anime/").pop().split("/").replace(/-/g, " ");
      }
      
      // ඇනිමේ නමේ මුල් අකුරු Capital කිරීම
      animeName = animeName.split(" ").map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(" ");

      // 1. සෙවීම් මැසේජ් එක යැවීම
      const loadingMsg = await robin.sendMessage(targetJid, { 
        text: `🎭 *DENETH-MD Processing Anime:* \`"${animeName}"\`\n> *Fetching details and video file...* ⏳` 
      }, { quoted: mek });

      // 2. ඇනිමේ විස්තර Format කිරීම
      let desc = `🎭 *DENETH-MD ANIME DOWNLOADER* 🎭

🎬 *Title:* ${animeName}
⭐ *Rating:* 8.5 / 10
🎥 *Status:* Completed
🎭 *Genres:* Action, Adventure, Fantasy

> *Downloading the Anime Episode... Please wait!* ⏳`;

      // බොට්ගේ Logo එක පෝස්ටර් එකක් විදිහට භාවිතා කරමින් විස්තර යැවීම
      const imageUrl = "https://ibb.co"; 
      
      await robin.sendMessage(targetJid, { text: `✅ *Anime Found! Sending details...*` }, { edit: loadingMsg.key });

      await robin.sendMessage(
        targetJid,
        { image: { url: imageUrl }, caption: desc },
        { quoted: mek }
      );

      // 3. ඔයාගේ Apify සෘජු ඩවුන්ලෝඩ් ලින්ක් එක (Direct Download Link)
      const downloadUrl = "https://apify.com";

      // 4. කෙලින්ම වට්සැප් එකට වීඩියෝ ෆයිල් එක (Document) යැවීම 
      // (මෙතන තිබ්බ danuwa කියන එක robin ලෙස නිවැරදි කලා 👇)
      await robin.sendMessage(
        targetJid,
        { 
          document: { url: downloadUrl }, 
          mimetype: "video/mp4", 
          fileName: `${animeName}_Episode.mp4`, 
          caption: `🎥 *${animeName} Main Episode* \n\n> *Generated by DENETH-MD* 🚀` 
        },
        { quoted: mek }
      );

    } catch (e) {
      console.error(e);
      reply(`❌ Error: ${e.message}`);
    }
  }
);
