const { cmd, commands } = require("../command");
const axios = require("axios");

cmd(
  {
    pattern: "apk",
    alias: ["downloadapk", "playstore"],
    react: "📦",
    desc: "Download APK files from Google Play Store links.",
    category: "download",
    filename: __filename,
  },
  async (
    danuwa,
    mek,
    m,
    {
      from,
      quoted,
      body,
      isCmd,
      command,
      args,
      q,
      reply,
    }
  ) => {
    try {
      if (!q) return reply("⚠️ *Please provide a Google Play Store app link or app ID!*");

      // ප්ලේ ස්ටෝර් ලින්ක් එකක් නම්, ඒකෙන් Package ID එක (com.xxx) වෙන් කර ගැනීම
      let appId = q;
      if (q.includes("id=")) {
        appId = q.split("id=")[1].split("&")[0];
      }

      const targetJid = typeof from === 'string' ? from : (mek.key.remoteJid || String(from));

      // 1. ඇප් එක සෙවීම සහ ඩවුන්ලෝඩ් කිරීම ආරම්භ කිරීමේ මැසේජ් එක
      const loadingMsg = await danuwa.sendMessage(targetJid, { 
        text: `📦 *DENETH-MD Fetching APK for ID:* \`"${appId}"\`\n> *Please wait...* ⏳` 
      }, { quoted: mek });

      // 2. APK බාගත කිරීම සඳහා විශ්වාසවන්ත සහ නොමිලේ දෙන පොදු API එකක් භාවිතා කිරීම
      const apiUrl = `https://dreaded.site{encodeURIComponent(appId)}`;
      const response = await axios.get(apiUrl);
      const resData = response.data;

      if (!resData || !resData.result || !resData.result.downloadUrl) {
        return await danuwa.sendMessage(targetJid, { 
          text: "❌ *Failed to download the APK. Please ensure the link/ID is correct or try again later.*", 
          edit: loadingMsg.key 
        });
      }

      const downloadUrl = resData.result.downloadUrl;
      const appName = resData.result.name || "Application";

      await danuwa.sendMessage(targetJid, { text: `✅ *APK Found! Sending document...*` }, { edit: loadingMsg.key });

      // 3. වට්සැප් එකට APK එක Document එකක් ලෙස සෘජුවම යැවීම
      await danuwa.sendMessage(
        targetJid,
        {
          document: { url: downloadUrl },
          mimetype: "application/vnd.android.package-archive",
          fileName: `${appName}.apk`,
          caption: `📦 *${appName} APK is ready!* \n\n> *Generated by DENETH-MD* 🚀`,
        },
        { quoted: mek }
      );

    } catch (e) {
      console.log("APK Downloader Error:", e);
      reply(`❌ *Error:* ${e.message} 😞`);
    }
  }
);
