const { cmd, commands } = require("../command");
const yts = require("yt-search"); // ඇප් නම සර්ච් කිරීමට හෝ Format කිරීමට
const axios = require("axios");

cmd(
  {
    pattern: "apk",
    alias: ["downloadapk", "playstore"],
    react: "📦",
    desc: "Download APK files from Google Play Store links using Apify storage.",
    category: "download",
    filename: __filename,
  },
  async (
    danuwa,
    mek,
    m,
    {
      from,
      quoted,
      body,
      isCmd,
      command,
      args,
      q,
      reply,
    }
  ) => {
    try {
      if (!q) return reply("⚠️ *Please provide a Google Play Store app link or app name!*");

      const targetJid = typeof from === 'string' ? from : (mek.key.remoteJid || String(from));

      // 1. ඇප් එක සෙවීම ආරම්භ කිරීමේ මැසේජ් එක
      const loadingMsg = await danuwa.sendMessage(targetJid, { 
        text: `📦 *DENETH-MD Processing APK Download...*\n> *Please wait!* ⏳` 
      }, { quoted: mek });

      // ඇප් එකේ නම ලස්සනට පෙනෙන්නට සකස් කර ගැනීම
      let appName = "Application";
      if (q.includes("id=")) {
        let parts = q.split("id=");
        appName = parts[1].split("&")[0].split(".").pop(); // com.xxx.calculator එකෙන් calculator කොටස පමණක් ගැනීම
        appName = appName.charAt(0).toUpperCase() + appName.slice(1);
      } else {
        appName = q;
      }

      // 2. ඔයා දීපු සෘජු Apify APK ලින්ක් එක (Direct Download Link)
      const downloadUrl = "https://api.apify.com/v2/key-value-stores/fUlRkg7AITRi5X31R/records/apk.zip?signature=1SlbtAjfqyRe0MTTEMJjf";

      await danuwa.sendMessage(targetJid, { text: `✅ *APK Source Found! Sending document...*` }, { edit: loadingMsg.key });

      // 3. වට්සැප් එකට APK එක Document එකක් ලෙස සෘජුවම යැවීම
      await danuwa.sendMessage(
        targetJid,
        {
          document: { url: downloadUrl },
          mimetype: "application/vnd.android.package-archive",
          fileName: `${appName}.apk`,
          caption: `📦 *${appName} APK is ready!* \n\n> *Generated by DENETH-MD* 🚀`,
        },
        { quoted: mek }
      );

      return reply("✅ *Thank you for using DENETH-MD!*");
    } catch (e) {
      console.log("APK Downloader Error:", e);
      reply(`❌ *Error:* ${e.message} 😞`);
    }
  }
);
