const { cmd, commands } = require("../command");
const config = require("../config");

cmd(
  {
    pattern: "menu",
    alias: ["getmenu"],
    react: "📔",
    desc: "Get simple welcome menu",
    category: "main",
    filename: __filename,
  },

  async (
    robin,
    mek,
    m,
    {
      from,
      sender,
      reply,
    }
  ) => {
    try {

      // ==========================================
      // SEND ONLY IMAGE WITH WELCOME TEXT & FOOTER
      // ==========================================
      await robin.sendMessage(
        from,
        {
          image: {
            url: "https://pmd-img2url.koyeb.app/v/2ede0d43f067446bdc1c095b38d29f70.jpg", // 👈 වැඩ කරන නිවැරදිම ලෝගෝ ලින්ක් එක දැම්මා
          },
          caption: "👋 *Hello welcome to DENETH-MD*\n\n> *Generated by DENETH-MD* 💢💥", // 👈 ඔයා ඉල්ලපු වැකිය ඉමෝජි එක්කම එකතු කළා
          contextInfo: {
            mentionedJid: sender ? [sender] : [],
            forwardingScore: 1000,
            isForwarded: true,
            forwardedNewsletterMessageInfo: {
              newsletterJid: "120363429118791328@newsletter",
              newsletterName: "DENETH 𝐌𝐃",
              serverMessageId: 143,
            },
          },
        },
        {
          quoted: mek,
        }
      );

    } catch (e) {
      console.error("MENU ERROR:", e);
      reply(`❌ Menu Error\n\n${e.message || e}`);
    }
  }
);
