const { cmd, commands } = require("../command");
const config = require("../config");

// =================================================================
// 👑 ප්‍රධාන මෙනු කමාන්ඩ් එක (.menu ගැසූ විට ක්‍රියාත්මක වන කොටස)
// =================================================================
cmd(
  {
    pattern: "menu",
    alias: ["getmenu", "allmenu"],
    react: "📔",
    desc: "Get advanced category selection menu",
    category: "main",
    filename: __filename,
  },

  async (robin, mek, m, { from, sender, reply }) => {
    try {
      const { generateWAMessageFromContent, proto, prepareWAMessageMedia } = require("@whiskeysockets/baileys");

      // 📋 "📋 OPEN MENU" එක එබුවම පෙනෙන කැටගරි ලැයිස්තුව
      const sections = [
        {
          title: "📋 DENETH-MD MENU CATEGORIES",
          rows: [
            { title: "MAIN MENU 📜", rowId: ".mainmenu", description: "Show core system commands" },
            { title: "AI MENU 🤖", rowId: ".aimenu", description: "AI commands and smart tools" },
            { title: "ANIME MENU 🎎", rowId: ".animemenu", description: "Anime images and wallpapers" },
            { title: "GROUP MENU 👥", rowId: ".groupmenu", description: "Group management commands" },
            { title: "CONVERT MENU 🔄", rowId: ".convertmenu", description: "Sticker and file converters" },
            { title: "DOWNLOAD MENU 📥", rowId: ".downloadmenu", description: "Social media video downloaders" },
            { title: "OTHER MENU ⚙️", rowId: ".othermenu", description: "Extra tools and features" }
          ]
        }
      ];

      // ඔයාගේ මුල්ම ලින්ක් එකෙන්ම ඉමේජ් එක සකස් කිරීම
      const mediaMessage = await prepareWAMessageMedia(
        { image: { url: "https://ibb.co" } }, 
        { upload: robin.waUploadToServer }
      );

      const msg = generateWAMessageFromContent(from, {
        viewOnceMessage: {
          message: {
            messageContextInfo: { deviceListMetadata: {}, deviceListMetadataVersion: 2 },
            interactiveMessage: proto.Message.InteractiveMessage.fromObject({
              body: proto.Message.InteractiveMessage.Body.fromObject({ 
                text: "👋 *Hello welcome to DENETH-MD*\n\n> *Generated by DENETH-MD* 💢" 
              }),
              footer: proto.Message.InteractiveMessage.Footer.fromObject({ text: "© Powered By Deneth MD" }),
              header: proto.Message.InteractiveMessage.Header.fromObject({
                hasMediaAttachment: true,
                imageMessage: mediaMessage.imageMessage
              }),
              nativeFlowMessage: proto.Message.InteractiveMessage.NativeFlowMessage.fromObject({
                buttons: [
                  {
                    "name": "single_select",
                    "buttonParamsJson": JSON.stringify({
                      "title": "📋 OPEN MENU",
                      "sections": sections
                    })
                  }
                ]
              }),
              contextInfo: {
                mentionedJid: sender ? [sender] : [],
                forwardingScore: 1000,
                isForwarded: true,
                forwardedNewsletterMessageInfo: {
                  newsletterJid: "120363429118791328@newsletter",
                  newsletterName: "DENETH 𝐌𝐃",
                  serverMessageId: 143,
                },
              },
            })
          }
        }
      }, { userJid: robin.user.jid, quoted: mek });

      await robin.relayMessage(from, msg.message, { messageId: msg.key.id });

    } catch (e) {
      console.error("MENU ERROR:", e);
      reply(`❌ Menu Error\n\n${e.message || e}`);
    }
  }
);

// =================================================================
// 📂 උප-මෙනු කමාන්ඩ්ස් (ලිස්ට් එකෙන් තෝරන ඒවාට රිප්ලයි කරන කොටස)
// =================================================================

// 1. MAIN MENU
cmd({ pattern: "mainmenu", dontAddCommandList: true, category: "main", filename: __filename }, async (conn, mek, m, { reply }) => {
    return reply(`📜 *DENETH-MD MAIN COMMANDS*\n\n.ping - Check bot speed\n.alive - Check system status\n.owner - Get owner contact\n.system - Show server info`);
});

// 2. AI MENU
cmd({ pattern: "aimenu", dontAddCommandList: true, category: "main", filename: __filename }, async (conn, mek, m, { reply }) => {
    return reply(`🤖 *DENETH-MD AI COMMANDS*\n\n.gpt <text> - Ask anything from ChatGPT\n.ai <text> - AI search engine\n.imagine <text> - Generate AI photo`);
});

// 3. ANIME MENU
cmd({ pattern: "animemenu", dontAddCommandList: true, category: "main", filename: __filename }, async (conn, mek, m, { reply }) => {
    return reply(`🎎 *DENETH-MD ANIME COMMANDS*\n\n.anime - Random anime photo\n.waifu - Get random waifu image\n.wallanime - Anime phone wallpapers`);
});

// 4. GROUP MENU
cmd({ pattern: "groupmenu", dontAddCommandList: true, category: "main", filename: __filename }, async (conn, mek, m, { reply }) => {
    return reply(`👥 *DENETH-MD GROUP COMMANDS*\n\n.kick <reply> - Remove a member\n.tagall - Mention all members\n.mute - Close group chat\n.unmute - Open group chat`);
});

// 5. CONVERT MENU
cmd({ pattern: "convertmenu", dontAddCommandList: true, category: "main", filename: __filename }, async (conn, mek, m, { reply }) => {
    return reply(`🔄 *DENETH-MD CONVERT COMMANDS*\n\n.sticker - Photo to sticker\n.tomp3 - Video to audio file\n.toimage - Sticker to normal photo`);
});

// 6. DOWNLOAD MENU (📦 ඔයා එවපු APK කමාන්ඩ් එක මෙතනට ඇතුළත් කළා!)
cmd({ pattern: "downloadmenu", dontAddCommandList: true, category: "main", filename: __filename }, async (conn, mek, m, { reply }) => {
    return reply(`📥 *DENETH-MD DOWNLOAD COMMANDS* 📥\n\n.apk <app name/link> - Android App Downloader 📦\n.fb <url> - Facebook video download\n.yt <url> - YouTube video/audio\n.tiktok <url> - TikTok video download`);
});

// 7. OTHER MENU
cmd({ pattern: "othermenu", dontAddCommandList: true, category: "main", filename: __filename }, async (conn, mek, m, { reply }) => {
    return reply(`⚙️ *DENETH-MD OTHER COMMANDS*\n\n.runtime - Show bot uptime\n.weather <city> - Get weather info\n.tourl <reply photo> - Image to web link`);
});
