const { cmd, commands } = require("../command");
const config = require("../config");

cmd(
  {
    pattern: "menu",
    alias: ["getmenu"],
    react: "📔",
    desc: "Get simple welcome menu",
    category: "main",
    filename: __filename,
  },

  async (
    robin,
    mek,
    m,
    {
      from,
      sender,
      reply,
    }
  ) => {
    try {
      // ==========================================
      // NATIVE FLOW SINGLE SELECT LIST MESSAGE
      // ==========================================
      const { generateWAMessageFromContent, proto, prepareWAMessageMedia } = require("@whiskeysockets/baileys");

      // 📋 ඔයා එවපු රූපයේ වගේම Open Menu එක ක්ලික් කලාම වැටෙන ලිස්ට් එක සකස් කිරීම
      const sections = [
        {
          title: "LUXALGO-MD MENU",
          rows: [
            { title: "MAIN MENU 📜", rowId: ".menu", description: "Show all commands list" },
            { title: "PING ⚡", rowId: ".ping", description: "Check bot speed status" },
            { title: "ALIVE STATUS 🧚‍♂️", rowId: ".alive", description: "Check bot uptime status" },
            { title: "BOT OWNER 👑", rowId: ".owner", description: "Get developer details" }
          ]
        }
      ];

      // ඔයාගේ මුල් ලින්ක් එකෙන්ම ඉමේජ් එක සකස් කිරීම
      const mediaMessage = await prepareWAMessageMedia(
        { image: { url: "https://ibb.co" } }, 
        { upload: robin.waUploadToServer }
      );

      const msg = generateWAMessageFromContent(from, {
        viewOnceMessage: {
          message: {
            messageContextInfo: {
              deviceListMetadata: {},
              deviceListMetadataVersion: 2
            },
            interactiveMessage: proto.Message.InteractiveMessage.fromObject({
              body: proto.Message.InteractiveMessage.Body.fromObject({
                text: "👋 *Hello welcome to DENETH-MD*\n\n> *Generated by DENETH-MD* 💢" // මුල්ම caption එක එකම අකුරක්වත් වෙනස් කර නැත
              }),
              footer: proto.Message.InteractiveMessage.Footer.fromObject({
                text: "⚡ LUXALGO-MD" // ඔයා එවපු රූපයේ තිබූ ෆුටර් එක
              }),
              header: proto.Message.InteractiveMessage.Header.fromObject({
                hasMediaAttachment: true,
                imageMessage: mediaMessage.imageMessage
              }),
              nativeFlowMessage: proto.Message.InteractiveMessage.NativeFlowMessage.fromObject({
                buttons: [
                  {
                    "name": "single_select",
                    "buttonParamsJson": JSON.stringify({
                      "title": "📋 OPEN MENU", // ඔයා එවපු ස්ක්‍රීන්ෂොට් එකේ තිබුණු නමමයි
                      "sections": sections
                    })
                  }
                ]
              }),
              contextInfo: {
                mentionedJid: sender ? [sender] : [],
                forwardingScore: 1000,
                isForwarded: true,
                forwardedNewsletterMessageInfo: {
                  newsletterJid: "120363429118791328@newsletter",
                  newsletterName: "DENETH 𝐌𝐃", // මුල් Newsletter විස්තර එලෙසම ඇත
                  serverMessageId: 143,
                },
              },
            })
          }
        }
      }, { userJid: robin.user.jid, quoted: mek });

      // මැසේජ් එක වට්ස්ඇප් වෙත යැවීම
      await robin.relayMessage(from, msg.message, { messageId: msg.key.id });

    } catch (e) {
      console.error("MENU ERROR:", e);
      reply(`❌ Menu Error\n\n${e.message || e}`);
    }
  }
);
