const { cmd, commands } = require("../command");
const yts = require("yt-search");
const { ytmp3 } = require("@vreden/youtube_scraper");

cmd(
  {
    pattern: "song",
    alias: ["play", "music", "ytmp3"],
    react: "🎶",
    desc: "Download YouTube songs as MP3 audio/document.",
    category: "download",
    filename: __filename,
  },
  async (
    danuwa,
    mek,
    m,
    {
      from,
      quoted,
      body,
      isCmd,
      command,
      args,
      q,
      isGroup,
      sender,
      senderNumber,
      botNumber2,
      botNumber,
      pushname,
      isMe,
      isOwner,
      groupMetadata,
      groupName,
      participants,
      groupAdmins,
      isBotAdmins,
      isAdmins,
      reply,
    }
  ) => {
    try {
      // 1. පරිශීලකයා නමක් හෝ ලින්ක් එකක් ලබා දී ඇත්දැයි බැලීම
      if (!q) return reply("⚠️ *Please provide a song name or a YouTube link!*");

      // JID එක සදහා ආරක්ෂිතව String එකක් ලබා ගැනීම
      const targetJid = typeof from === 'string' ? from : (mek.key.remoteJid || String(from));

      // 2. සින්දුව සෙවීම ආරම්භ කළ බව පෙන්වීම
      const loadingMsg = await danuwa.sendMessage(targetJid, { 
        text: `🎵 *DENETH-MD Searching Your Song...*\n\`"${q}"\`` 
      }, { quoted: mek });

      const search = await yts(q);
      if (!search.videos || search.videos.length === 0) {
        return await danuwa.sendMessage(targetJid, { text: "❌ *Song not found! Please check the name and try again.*", edit: loadingMsg.key });
      }
      
      const data = search.videos[0];
      const url = data.url;

      // 3. සින්දුවේ විස්තර ලස්සනට Format කිරීම
      let desc = `*🎶 DENETH-MD SONG DOWNLOADER 🎶*

🎬 *Title:* ${data.title}
⏱️ *Duration:* ${data.timestamp}
📅 *Uploaded:* ${data.ago}
👀 *Views:* ${data.views.toLocaleString()}
🔗 *URL:* ${data.url}

> *Downloading your audio... Please wait!* ⏳`;

      // විස්තර පත්‍රිකාව Thumbnail එක සමඟ යැවීම සහ කලින් සෙවුම් මැසේජ් එක මකා දැමීම/වෙනස් කිරීම
      await danuwa.sendMessage(targetJid, { text: `✅ *Song Found! Sending details...*` }, { edit: loadingMsg.key });
      
      await danuwa.sendMessage(
        targetJid,
        { image: { url: data.thumbnail }, caption: desc },
        { quoted: mek }
      );

      // 4. කාලය පරීක්ෂා කිරීම (විනාඩි 30 සීමාව)
      let durationParts = data.timestamp.split(":").map(Number);
      let totalSeconds =
        durationParts.length === 3
          ? durationParts[0] * 3600 + durationParts[1] * 60 + durationParts[2]
          : durationParts[0] * 60 + durationParts[1];

      if (totalSeconds > 1800) {
        return reply("⏳ *Sorry, audio files longer than 30 minutes are not supported.*");
      }

      // 5. යූටියුබ් වෙතින් සින්දුව ඩවුන්ලෝඩ් කර ගැනීම
      const quality = "192";
      const songData = await ytmp3(url, quality);

      if (!songData || !songData.download || !songData.download.url) {
        return reply("❌ *Failed to fetch download link. Please try again later.*");
      }

      // 6. වට්සැප් එකට Audio එකක් ලෙස යැවීම
      await danuwa.sendMessage(
        targetJid,
        {
          audio: { url: songData.download.url },
          mimetype: "audio/mp4",
        },
        { quoted: mek }
      );

      // 7. වට්සැප් එකට Document එකක් ලෙස යැවීම
      await danuwa.sendMessage(
        targetJid,
        {
          document: { url: songData.download.url },
          mimetype: "audio/mpeg",
          fileName: `${data.title}.mp3`,
          caption: "🎶 *Your song document is ready!* \n\n> *Generated by DENETH-MD* 🚀",
        },
        { quoted: mek }
      );

      return reply("✅ *Thank you for using DENETH-MD!*");
    } catch (e) {
      console.log(e);
      reply(`❌ *Error:* ${e.message} 😞`);
    }
  }
);
