const { cmd, commands } = require("../command");
const config = require("../config");

cmd(
  {
    pattern: "url",
    alias: ["botlink", "links"],
    react: "🔗",
    desc: "Get bot welcome link with image",
    category: "main",
    filename: __filename,
  },

  async (
    conn,
    mek,
    m,
    {
      from,
      sender,
      reply,
    }
  ) => {
    try {

      // ==========================================
      // IMAGE WITH WELCOME TEXT & GENERATED FOOTER
      // ==========================================
      await conn.sendMessage(
        from,
        {
          image: {
            url: "https://telegra.ph", // ඔබේ බොට් ලෝගෝව
          },
          caption: "👋 *Hello welcome to DENETH-MD*\n\n> *Generated by DENETH-MD* 🤖⚡",
          contextInfo: {
            mentionedJid: sender ? [sender] : [],
            forwardingScore: 1000,
            isForwarded: true,
            forwardedNewsletterMessageInfo: {
              newsletterJid: "120363429118791328@newsletter",
              newsletterName: "DENETH 𝐌𝐃",
              serverMessageId: 143,
            },
          },
        },
        {
          quoted: mek,
        }
      );

    } catch (e) {
      console.error("URL COMMAND ERROR:", e);
      reply(`❌ Url Error\n\n${e.message || e}`);
    }
  }
);
