const { cmd, commands } = require("../command");
const yts = require("yt-search");
const axios = require("axios");
const config = require("../config");

cmd(
  {
    pattern: "video",
    alias: ["playvideo", "ytmp4"],
    react: "🎬",
    desc: "Download YouTube videos as MP4 format.",
    category: "download",
    filename: __filename,
  },
  async (
    danuwa,
    mek,
    m,
    {
      from,
      quoted,
      body,
      isCmd,
      command,
      args,
      q,
      isGroup,
      sender,
      senderNumber,
      botNumber2,
      botNumber,
      pushname,
      isMe,
      isOwner,
      groupMetadata,
      groupName,
      participants,
      groupAdmins,
      isBotAdmins,
      isAdmins,
      reply,
    }
  ) => {
    try {
      if (!q) return reply("⚠️ *Please provide a video name or a YouTube link!*");

      const targetJid = typeof from === 'string' ? from : (mek.key.remoteJid || String(from));

      // 1. වීඩියෝව සෙවීම ආරම්භ කිරීම
      const loadingMsg = await danuwa.sendMessage(targetJid, { 
        text: `🎬 *DENETH-MD Searching Your Video...*\n\`"${q}"\`` 
      }, { quoted: mek });

      const search = await yts(q);
      if (!search.videos || search.videos.length === 0) {
        return await danuwa.sendMessage(targetJid, { text: "❌ *Video not found! Please check the name and try again.*", edit: loadingMsg.key });
      }
      
      const data = search.videos[0]; // නිවැරදිව මුල්ම වීඩියෝව තෝරාගැනීම

      // වීඩියෝ විස්තර Format කිරීම
      let desc = `*🎬 DENETH-MD VIDEO DOWNLOADER 🎬*

🎬 *Title:* ${data.title}
⏱️ *Duration:* ${data.timestamp}
📅 *Uploaded:* ${data.ago}
👀 *Views:* ${data.views.toLocaleString()}
🔗 *URL:* ${data.url}

> *Downloading your MP4 video... Please wait!* ⏳`;

      await danuwa.sendMessage(targetJid, { text: `✅ *Video Found! Sending details...*` }, { edit: loadingMsg.key });
      
      await danuwa.sendMessage(
        targetJid,
        { image: { url: data.thumbnail }, caption: desc },
        { quoted: mek }
      );

      // 2. ඔයා ඉල්ලපු සෘජු Apify ලින්ක් එක (Direct Download Link)
      const downloadUrl = "https://apify.com";

      // 3. වට්සැප් එකට වීඩියෝ එකක් ලෙස සෘජුවම යැවීම
      await danuwa.sendMessage(
        targetJid,
        {
          video: { url: downloadUrl },
          mimetype: "video/mp4",
          caption: "🎶 *Your video is ready!* \n\n> *Generated by DENETH-MD* 🚀",
        },
        { quoted: mek }
      );

      return reply("✅ *Thank you for using DENETH-MD!*");
    } catch (e) {
      console.log(e);
      reply(`❌ *Error:* ${e.message} 😞`);
    }
  }
);
