const { cmd, commands } = require("../command");
const yts = require("yt-search");
const axios = require("axios");
const config = require("../config");

cmd(
  {
    pattern: "video",
    alias: ["playvideo", "ytmp4"],
    react: "🎬",
    desc: "Download YouTube videos as MP4 format.",
    category: "download",
    filename: __filename,
  },
  async (
    danuwa,
    mek,
    m,
    {
      from,
      quoted,
      body,
      isCmd,
      command,
      args,
      q,
      isGroup,
      sender,
      senderNumber,
      botNumber2,
      botNumber,
      pushname,
      isMe,
      isOwner,
      groupMetadata,
      groupName,
      participants,
      groupAdmins,
      isBotAdmins,
      isAdmins,
      reply,
    }
  ) => {
    try {
      if (!q) return reply("⚠️ *Please provide a video name or a YouTube link!*");

      const targetJid = typeof from === 'string' ? from : (mek.key.remoteJid || String(from));

      // 1. වීඩියෝව සෙවීම ආරම්භ කිරීම
      const loadingMsg = await danuwa.sendMessage(targetJid, { 
        text: `🎬 *DENETH-MD Searching Your Video...*\n\`"${q}"\`` 
      }, { quoted: mek });

      const search = await yts(q);
      if (!search.videos || search.videos.length === 0) {
        return await danuwa.sendMessage(targetJid, { text: "❌ *Video not found! Please check the name and try again.*", edit: loadingMsg.key });
      }
      
      const data = search.videos[0]; // නිවැරදිව මුල්ම වීඩියෝව තෝරාගැනීම
      const url = data.url;

      // වීඩියෝ විස්තර Format කිරීම
      let desc = `*🎬 DENETH-MD VIDEO DOWNLOADER 🎬*

🎬 *Title:* ${data.title}
⏱️ *Duration:* ${data.timestamp}
📅 *Uploaded:* ${data.ago}
👀 *Views:* ${data.views.toLocaleString()}
🔗 *URL:* ${data.url}

> *Downloading your MP4 video... Please wait!* ⏳`;

      await danuwa.sendMessage(targetJid, { text: `✅ *Video Found! Sending details...*` }, { edit: loadingMsg.key });
      
      await danuwa.sendMessage(
        targetJid,
        { image: { url: data.thumbnail }, caption: desc },
        { quoted: mek }
      );

      // 4. කාලය පරීක්ෂා කිරීම (විනාඩි 30 සීමාව)
      let durationParts = data.timestamp.split(":").map(Number);
      let totalSeconds =
        durationParts.length === 3
          ? durationParts[0] * 3600 + durationParts[1] * 60 + durationParts[2]
          : durationParts[0] * 60 + durationParts[1];

      if (totalSeconds > 1800) {
        return reply("⏳ *Sorry, audio files longer than 30 minutes are not supported.*");
      }

      // 5. යූටියුබ් වෙතින් සින්දුව ඩවුන්ලෝඩ් කර ගැනීම
      const quality = "192";
      const songData = await ytmp3(url, quality);

      if (!songData || !songData.download || !songData.download.url) {
        return reply("❌ *Failed to fetch download link. Please try again later.*");
      }

      // 6. වට්සැප් එකට Audio එකක් ලෙස යැවීම
      await danuwa.sendMessage(
        targetJid,
        {
          audio: { url: songData.download.url },
          mimetype: "audio/mp4",
        },
        { quoted: mek }
      );

      // 7. වට්සැප් එකට Document එකක් ලෙස යැවීම
      await danuwa.sendMessage(
        targetJid,
        {
          document: { url: songData.download.url },
          mimetype: "audio/mpeg",
          fileName: `${data.title}.mp3`,
          caption: "🎶 *Your video document is ready!* \n\n> *Generated by DENETH-MD* 🚀",
        },
        { quoted: mek }
      );

      return reply("✅ *Thank you for using DENETH-MD!*");
    } catch (e) {
      console.log(e);
      reply(`❌ *Error:* ${e.message} 😞`);
    }
  }
);
