const { cmd } = require("../command");
const yts = require("yt-search");

cmd(
  {
    pattern: "yts",
    alias: ["ytsearch", "youtubesearch", "search"],
    react: "🔎",
    desc: "Search YouTube videos dynamically.",
    category: "search",
    filename: __filename,
  },
  async (
    danuwa,
    mek,
    m,
    {
      from,
      quoted,
      q,
      reply,
    }
  ) => {
    try {
      // JID එක සඳහා ආරක්ෂිතව String අගයක් ලබා ගැනීම (Crashes වැළැක්වීමට)
      const targetJid = typeof from === 'string' ? from : (mek.key.remoteJid || String(from));

      // 1. පරිශීලකයා සෙවිය යුතු වචනයක් ලබා දී ඇත්දැයි බැලීම
      if (!q) return reply("⚠️ *Please provide a search query!*\n\n*Example:* `.yts lelena` or `.yts dynamic songs`");

      // 2. සෙවුම ආරම්භ කළ බව පෙන්වීමට පණිවිඩයක් යැවීම
      const loadingMsg = await danuwa.sendMessage(targetJid, { 
        text: `🔎 *DENETH-MD Searching YouTube for:* \`"${q}"\`...` 
      }, { quoted: mek });

      // 3. yt-search හරහා දත්ත ලබා ගැනීම
      const search = await yts(q);

      if (!search || !search.all || search.all.length === 0) {
        return await danuwa.sendMessage(targetJid, { 
          text: "❌ *No results found on YouTube. Please try another keyword.*", 
          edit: loadingMsg.key 
        });
      }

      // මුල් ප්‍රතිඵල 10 වෙන් කරගෙන ලස්සන UI එකකට Format කිරීම
      const results = search.videos.slice(0, 10); 
      let formattedResults = results.map((v, i) => (
        `🔹 *${i + 1}. ${v.title}*\n✨ ${v.ago} | ⌛ ${v.timestamp} | 👁️ ${v.views.toLocaleString()} views\n🔗 ${v.url}`
      )).join("\n\n");

      const caption = `*🌤️ DENETH-MD YOUTUBE SEARCH 🌤️*
───────────────────────────
🔎 *Query*: ${q}

${formattedResults}

> *Generated by DENETH-MD* 🚀`;

      // සෙවුම සාර්ථක වූ පසු ලෝඩින් මැසේජ් එක යාවත්කාලීන කිරීම
      await danuwa.sendMessage(targetJid, { text: `✅ *Search completed! Sending results...*` }, { edit: loadingMsg.key });

      // පින්තූරය සමඟ සෙවුම් ප්‍රතිඵල යැවීම
      await danuwa.sendMessage(
        targetJid,
        {
          image: {
            url: "https://github.com/DANUWA-MD/DANUWA-MD/blob/main/images/yts.png?raw=true",
          },
          caption,
        },
        { quoted: mek }
      );

    } catch (err) {
      console.error(err);
      const targetJid = typeof from === 'string' ? from : (mek.key.remoteJid || String(from));
      await danuwa.sendMessage(targetJid, { text: "❌ *An error occurred while searching YouTube.*" }, { quoted: mek });
    }
  }
);
