const { cmd } = require('../command');
const axios = require('axios');

cmd({
    pattern: "weather",
    alias: ["climate", "කාලගුණය"],
    desc: "ඕනෑම නගරයක වත්මන් කාලගුණ තොරතුරු ලබා ගැනීම.",
    category: "main",
    filename: __filename
},
async (conn, mek, from, options) => {
    try {
        // JID අගය String එකක් බවට තහවුරු කර ගැනීම
        const targetJid = typeof from === 'string' ? from : (mek.key.remoteJid || String(from));
        
        // පරිශීලකයා ඇතුළත් කළ නගරයේ නම ලබා ගැනීම
        const args = options.args;
        if (!args || args.length === 0) {
            return await conn.sendMessage(targetJid, { text: "⚠️ කරුණාකර නගරයක නමක් ඇතුළත් කරන්න!\n\n*උදාහරණ:* `.weather Colombo` හෝ `.weather Galle`" }, { quoted: mek });
        }

        const city = args.join(" ");
        
        // කාලගුණ API එකෙන් තොරතුරු ලබා ගැනීම
        const response = await axios.get(`https://wttr.in/${encodeURIComponent(city)}?format=j1`);
        const weatherData = response.data;

        // දත්ත ලබා ගැනීමේදී නිවැරදිව Array Index [0] භාවිත කිරීම (දෝෂය මඟහරවා ගැනීමට)
        const currentCondition = weatherData.current_condition[0];
        const tempC = currentCondition.temp_C;
        const tempF = currentCondition.temp_F;
        const humidity = currentCondition.humidity;
        const windSpeed = currentCondition.windspeedKmph;
        const weatherDesc = currentCondition.weatherDesc[0].value;
        const observationTime = currentCondition.observation_time;

        const nearestArea = weatherData.nearest_area[0];
        const areaName = nearestArea.areaName[0].value;
        const country = nearestArea.country[0].value;

        // මැසේජ් එක ලස්සනට සැකසීම
        const weatherMessage = `*🌤️ DENETH-MD WEATHER REPORT 🌤️*

📍 *Location:* ${areaName}, ${country}
🌡️ *Temperature:* ${tempC}°C (${tempF}°F)
☁️ *Condition:* ${weatherDesc}
💧 *Humidity:* ${humidity}%
💨 *Wind Speed:* ${windSpeed} Km/h
🕒 *Updated Time:* ${observationTime}

> *Generated by DENETH-MD* 🚀`;

        // ප්‍රතිඵලය වට්සැප් මැසේජ් එකක් ලෙස යැවීම
        await conn.sendMessage(targetJid, { text: weatherMessage }, { quoted: mek });

    } catch (e) {
        console.log("Weather Command Error: ", e);
        const targetJid = typeof from === 'string' ? from : (mek.key.remoteJid || String(from));
        await conn.sendMessage(targetJid, { text: "❌ එම නගරය සොයා ගැනීමට නොහැකි වුණා. කරුණාකර ඉංග්‍රීසි අකුරින් නම නිවැරදිව ඇතුළත් කරන්න. (උදා: Galle, Jaffna, Kandy)" }, { quoted: mek });
    }
});
