name: DILA-MD Bot
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350 
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # cache: 'npm'  <-- මේක අයින් කරා

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg imagemagick

      - name: Start Bot
        run: node index.js
        env:
          SESSION_ID: ${{ secrets.SESSION_ID }}
          OWNER_NUMBER: ${{ secrets.OWNER_NUMBER }}
