name: DILA-MD CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          ffmpeg -version

      - name: Check SESSION_ID
        env:
          SESSION_ID: ${{ secrets.SESSION_ID }}
        run: |
          if [ -z "$SESSION_ID" ]; then
            echo "❌ SESSION_ID is missing"
            exit 1
          fi
          echo "✅ SESSION_ID is set"

      - name: Start DILA-MD
        env:
          SESSION_ID: ${{ secrets.SESSION_ID }}
        run: node index.js
